2014-04-15 06:18:10 Error: [NotFoundException] Invalid post
Request URL: /cakephp247/posts/view/5.
Stack Trace:
#0 [internal function]: PostsController->view('5.')
#1 D:\GitProjects\cakephp247\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#2 D:\GitProjects\cakephp247\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#3 D:\GitProjects\cakephp247\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#4 D:\GitProjects\cakephp247\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-15 06:18:27 Error: [NotFoundException] Invalid post
Request URL: /cakephp247/posts/view/5
Stack Trace:
#0 [internal function]: PostsController->view('5')
#1 D:\GitProjects\cakephp247\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#2 D:\GitProjects\cakephp247\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#3 D:\GitProjects\cakephp247\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#4 D:\GitProjects\cakephp247\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-15 06:21:16 Error: [NotFoundException] Invalid post
Request URL: /cakephp247/posts/view/5
Stack Trace:
#0 [internal function]: PostsController->view('5')
#1 D:\GitProjects\cakephp247\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#2 D:\GitProjects\cakephp247\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#3 D:\GitProjects\cakephp247\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#4 D:\GitProjects\cakephp247\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-15 06:21:37 Error: [NotFoundException] Invalid post
Request URL: /cakephp247/posts/view/5
Stack Trace:
#0 [internal function]: PostsController->view('5')
#1 D:\GitProjects\cakephp247\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#2 D:\GitProjects\cakephp247\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#3 D:\GitProjects\cakephp247\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#4 D:\GitProjects\cakephp247\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-15 06:21:57 Error: [NotFoundException] Invalid post
Request URL: /cakephp247/posts/view/5
Stack Trace:
#0 [internal function]: PostsController->view('5')
#1 D:\GitProjects\cakephp247\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#2 D:\GitProjects\cakephp247\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#3 D:\GitProjects\cakephp247\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#4 D:\GitProjects\cakephp247\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-15 06:22:52 Error: [NotFoundException] Invalid post
Request URL: /cakephp247/posts/view/5
Stack Trace:
#0 [internal function]: PostsController->view('5')
#1 D:\GitProjects\cakephp247\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#2 D:\GitProjects\cakephp247\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#3 D:\GitProjects\cakephp247\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#4 D:\GitProjects\cakephp247\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-15 06:45:50 Error: Fatal Error (1): Call to a member function allow() on a non-object in [D:\GitProjects\cakephp247\app\Controller\UsersController.php, line 7]
2014-04-15 06:45:50 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /cakephp247/users/add
Stack Trace:
#0 D:\GitProjects\cakephp247\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\GitProjects\...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\GitProjects\...', 7, Array)
#2 D:\GitProjects\cakephp247\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\GitProjects\...', 7, Array)
#3 D:\GitProjects\cakephp247\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-15 06:46:39 Error: [MissingViewException] View file "D:\GitProjects\cakephp247\app\View\Users\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'D:\\GitProjects\\cakephp247\\app\\View\\Users\\index.ctp',
)
Request URL: /cakephp247/users
Stack Trace:
#0 D:\GitProjects\cakephp247\lib\Cake\View\View.php(463): View->_getViewFileName(NULL)
#1 D:\GitProjects\cakephp247\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 D:\GitProjects\cakephp247\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#3 D:\GitProjects\cakephp247\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 D:\GitProjects\cakephp247\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-22 08:00:04 Error: [MissingViewException] View file "D:\GitProjects\cakephp247\app\View\Users\view.ctp" is missing.
Exception Attributes: array (
  'file' => 'D:\\GitProjects\\cakephp247\\app\\View\\Users\\view.ctp',
)
Request URL: /cakephp247/users/view/2
Stack Trace:
#0 D:\GitProjects\cakephp247\lib\Cake\View\View.php(463): View->_getViewFileName(NULL)
#1 D:\GitProjects\cakephp247\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 D:\GitProjects\cakephp247\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#3 D:\GitProjects\cakephp247\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 D:\GitProjects\cakephp247\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-22 09:37:00 Error: Fatal Error (1): Call to a member function allow() on a non-object in [D:\GitProjects\cakephp247\app\Controller\UsersController.php, line 9]
2014-04-22 09:37:00 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /cakephp247/users/logout
Stack Trace:
#0 D:\GitProjects\cakephp247\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\GitProjects\...', 9)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\GitProjects\...', 9, Array)
#2 D:\GitProjects\cakephp247\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\GitProjects\...', 9, Array)
#3 D:\GitProjects\cakephp247\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-22 09:37:57 Error: Fatal Error (1): Call to a member function logout() on a non-object in [D:\GitProjects\cakephp247\app\Controller\UsersController.php, line 15]
2014-04-22 09:37:57 Error: [FatalErrorException] Call to a member function logout() on a non-object
Request URL: /cakephp247/users/logout
Stack Trace:
#0 D:\GitProjects\cakephp247\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\GitProjects\...', 15)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\GitProjects\...', 15, Array)
#2 D:\GitProjects\cakephp247\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\GitProjects\...', 15, Array)
#3 D:\GitProjects\cakephp247\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-22 11:12:59 Error: [MissingActionException] Action PostsController::login() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'login',
)
Request URL: /cakephp247/posts/login
Stack Trace:
#0 D:\GitProjects\cakephp247\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 D:\GitProjects\cakephp247\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#2 D:\GitProjects\cakephp247\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-22 11:21:37 Error: Fatal Error (1): Call to a member function user() on a non-object in [D:\GitProjects\cakephp247\app\Controller\PostsController.php, line 56]
2014-04-22 11:21:37 Error: [FatalErrorException] Call to a member function user() on a non-object
Request URL: /cakephp247/posts/edit/1
Stack Trace:
#0 D:\GitProjects\cakephp247\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\GitProjects\...', 56)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\GitProjects\...', 56, Array)
#2 D:\GitProjects\cakephp247\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\GitProjects\...', 56, Array)
#3 D:\GitProjects\cakephp247\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
